[phases.setup]
nixPkgs = [
    "nodejs-18_x",
    "python3",
    "python3Packages.pip",
    "gcc",
    "nodePackages.pnpm"
]

[phases.install]
cmds = [
    "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = [
    "pnpm run build"
]

[start]
cmd = "pnpm run start:prod"

# Agregar estas l√≠neas para asegurar crypto
[environment]
NODE_OPTIONS = "--experimental-global-webcrypto"