[phases.setup]
nixPkgs = [
    "nodejs-18_x",
    "python3",
    "python3Packages.pip",
    "gcc"
]

[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@9.15.0 --activate",
    "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = [
    "pnpm run build"
]

[start]
cmd = "node dist/main"